### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RyanClarke2** [Frago9876543210/morph#1]
09.04 19:45:15 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /plugins/morph-master/src/morph/main.php on line 141" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 545
09.04 19:45:15 [Server] Server thread/CRITICAL Unhandled exception executing command 'morph add Chicken' in morph: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /plugins/morph-master/src/morph/main.php on line 141
 Ryanshaw2 > /morph add Chicken

Could you fix this please?

**Comment by Frago9876543210** [comment]
@RyanClarke2 okey, I update plugin

**Comment by RyanClarke2** [comment]
ok thank you
